version: 2.1
# orbs:
#     node: circleci/node@1.1.6
# jobs:
#     build:
#         docker:
#             - image: circleci/node:12.2.0
#             - image: circleci/node:jessie-browsers
#             - image: selenium/standalone-chrome-debug
#             # - image: circleci/node:10.16.3
#             # - image: circleci/openjdk:11.0.3-jdk-stretch
#             # - image: tenjaa/java-chrome-nodejs
#             #  atools/chrome-headless:java8-node12-latest
#             # - image: circleci/node:10.12-browsers
#             # - image: selenium/standalone-chrome
#         executor:
#             name: node/default
#         steps:
#             - checkout
#             - node/with-cache:
#                   steps:
#                       - run: npm install
#                       - run: npm test
# workflows:
#     build:
#         jobs:
#             - build
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: selenium/hub
        name: hub
      - image: selenium/node-firefox
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm run start
          background: true
        
      # run tests!
      - run: npm run test

      - store_artifacts:
          path: ./errorShots/
          when: always