version: 2.1

orbs:
    node: circleci/node@1.1.6
jobs:
    build:
        docker:
            # - image: atools/chrome-headless:java8-node12-latest
            - image: circleci/node:12.2.0
        # build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      # - run: sudo apt-get install libnss3-dev
                      - run: npm test
workflows:
    build:
        jobs:
            - build
