version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build:
        docker:
            - image: circleci/node:12.2.0
            # - image: circleci/node:jessie-browsers
            - image: selenium/standalone-chrome-debug
            # - image: circleci/node:10.16.3
            # - image: circleci/openjdk:11.0.3-jdk-stretch
            # - image: tenjaa/java-chrome-nodejs
            #  atools/chrome-headless:java8-node12-latest
            # - image: circleci/node:10.12-browsers
            # - image: selenium/standalone-chrome
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm test
workflows:
    build:
        jobs:
            - build
